_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [ 256, 256 ]
  SIZE_TEST: [ 256, 256 ]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True

SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-6
  # IMS_PER_BATCH: 120
  IMS_PER_BATCH: 16
  MAX_EPOCH: 90
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 5

  SCHED: CosineAnnealingLR
  DELAY_EPOCHS: 30
  T_MAX: 60 #停止学习率衰减

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
  # NUM_INSTANCE: 30
  NUM_INSTANCE: 4

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veri/1003_ablation_erase95_dhg_gn_gradcam
