_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

  HEADS:
    POOL_LAYER: GeneralizedMeanPooling

  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)


SOLVER:
  IMS_PER_BATCH: 128
  MAX_EPOCH: 120
  BASE_LR: 0.0001
  WARMUP_ITERS: 5000

  SCHED: MultiStepLR
  STEPS: [30, 70, 90]
  GAMMA: 0.1

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veriwild/baseline_gn_cv2nlp
